<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-TCEP82C" name="org.test.Test2" tests="10" failures="1" timestamp="25 Jun 2021 10:07:20 GMT" time="0.023" errors="0">
  <testcase name="tc23" time="0.002" classname="org.test.Test2">
    <skipped/>
  </testcase> <!-- tc23 -->
  <testcase name="tc23" time="0.003" classname="org.test.Test2">
    <skipped/>
  </testcase> <!-- tc23 -->
  <testcase name="tc23" time="0.001" classname="org.test.Test2">
    <skipped/>
  </testcase> <!-- tc23 -->
  <testcase name="tc24" time="0.001" classname="org.test.Test2"/>
  <testcase name="tc23" time="0.001" classname="org.test.Test2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.test.Test2.tc23(Test2.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc23 -->
  <testcase name="tc22" time="0.001" classname="org.test.Test2"/>
  <testcase name="tc20" time="0.010" classname="org.test.Test2"/>
  <testcase name="tc23" time="0.002" classname="org.test.Test2">
    <skipped/>
  </testcase> <!-- tc23 -->
  <testcase name="tc23" time="0.001" classname="org.test.Test2">
    <skipped/>
  </testcase> <!-- tc23 -->
  <testcase name="tc21" time="0.001" classname="org.test.Test2"/>
</testsuite> <!-- org.test.Test2 -->
